version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - APP_NAME=${APP_NAME}
      - PORT=${PORT}
      - DATABASE_URL=postgres://myuser:mypassword@db:5432/unleashed-db
      - JWT_SECRET=${JWT_SECRET}
      - RESET_DB=${RESET_DB}
      - SMTP_SERVICE=${SMTP_SERVICE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - TEST_EMAIL=${TEST_EMAIL}
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
