version: "3.8"
services:
#  app:
#    build: .
#    ports:
#      - "3000:3000"
#    environment:
#      - DATABASE_URL=postgresql://myuser:mypassword@db:5432/mydb
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres:
